/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipelines */
        get: operations["listPipelines"];
        put?: never;
        /** Create pipeline */
        post: operations["createPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve pipeline */
        get: operations["getPipeline"];
        put?: never;
        post?: never;
        /** Delete pipeline */
        delete: operations["deletePipeline"];
        options?: never;
        head?: never;
        /** Update pipeline */
        patch: operations["updatePipeline"];
        trace?: never;
    };
    "/pipelines/{id}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set up destination schema for a pipeline
         * @description Creates destination tables and applies migrations. Safe to call multiple times.
         */
        post: operations["setupPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/teardown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tear down destination schema for a pipeline
         * @description Drops destination tables. Irreversible.
         */
        post: operations["teardownPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check connector connection for a pipeline
         * @description Validates the source/destination config and tests connectivity.
         */
        get: operations["checkPipeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read records from the pipeline source
         * @description Streams NDJSON messages (records, state, catalog). Optional NDJSON body provides input.
         */
        post: operations["readPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write records to the pipeline destination
         * @description Reads NDJSON messages from the request body and writes them to the destination.
         */
        post: operations["writePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run pipeline (read → write)
         * @description Without a request body, reads from the source connector and writes to the destination (backfill mode). With an NDJSON request body, uses the provided messages as input instead of reading from the source (push mode — e.g. piped webhook events).
         */
        post: operations["syncPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a running pipeline (Temporal mode only)
         * @description Signals the Temporal workflow to pause. The pipeline will stop processing after the current batch completes. Requires --temporal-address.
         */
        post: operations["pausePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused pipeline (Temporal mode only)
         * @description Signals the Temporal workflow to resume. Requires --temporal-address.
         */
        post: operations["resumePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{pipeline_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a Stripe webhook event
         * @description Receives a raw Stripe webhook event, verifies its signature using the pipeline's webhook secret, and enqueues it for processing by the active pipeline.
         */
        post: operations["pushWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        ok: true;
                    };
                };
            };
        };
    };
    listPipelines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of pipelines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            source: {
                                name: string;
                            } & {
                                [key: string]: unknown;
                            };
                            destination: {
                                name: string;
                            } & {
                                [key: string]: unknown;
                            };
                            streams?: {
                                name: string;
                                /** @enum {string} */
                                sync_mode?: "incremental" | "full_refresh";
                            }[];
                        }[];
                        has_more: boolean;
                    };
                };
            };
        };
    };
    createPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    source: {
                        name: string;
                    } & {
                        [key: string]: unknown;
                    };
                    destination: {
                        name: string;
                    } & {
                        [key: string]: unknown;
                    };
                    streams?: {
                        name: string;
                        /** @enum {string} */
                        sync_mode?: "incremental" | "full_refresh";
                    }[];
                };
            };
        };
        responses: {
            /** @description Created pipeline */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        source: {
                            name: string;
                        } & {
                            [key: string]: unknown;
                        };
                        destination: {
                            name: string;
                        } & {
                            [key: string]: unknown;
                        };
                        streams?: {
                            name: string;
                            /** @enum {string} */
                            sync_mode?: "incremental" | "full_refresh";
                        }[];
                    };
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    getPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieved pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        source: {
                            name: string;
                        } & {
                            [key: string]: unknown;
                        };
                        destination: {
                            name: string;
                        } & {
                            [key: string]: unknown;
                        };
                        streams?: {
                            name: string;
                            /** @enum {string} */
                            sync_mode?: "incremental" | "full_refresh";
                        }[];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    deletePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {boolean} */
                        deleted: true;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    updatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    source?: {
                        name: string;
                    } & {
                        [key: string]: unknown;
                    };
                    destination?: {
                        name: string;
                    } & {
                        [key: string]: unknown;
                    };
                    streams?: {
                        name: string;
                        /** @enum {string} */
                        sync_mode?: "incremental" | "full_refresh";
                    }[];
                };
            };
        };
        responses: {
            /** @description Updated pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        source: {
                            name: string;
                        } & {
                            [key: string]: unknown;
                        };
                        destination: {
                            name: string;
                        } & {
                            [key: string]: unknown;
                        };
                        streams?: {
                            name: string;
                            /** @enum {string} */
                            sync_mode?: "incremental" | "full_refresh";
                        }[];
                    };
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    setupPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup complete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    teardownPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Teardown complete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    checkPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        source: {
                            /** @enum {string} */
                            status: "succeeded" | "failed";
                            message?: string;
                        };
                        destination: {
                            /** @enum {string} */
                            status: "succeeded" | "failed";
                            message?: string;
                        };
                    };
                };
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    readPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of sync messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    writePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-ndjson": string;
            };
        };
        responses: {
            /** @description NDJSON stream of write result messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            /** @description Missing request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    syncPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of sync messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    pausePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pause signal sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
            /** @description Pause requires Temporal mode */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    resumePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resume signal sent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
            /** @description Resume requires Temporal mode */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: unknown;
                    };
                };
            };
        };
    };
    pushWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "ok";
                };
            };
        };
    };
}
