#!/usr/bin/env bun
/**
 * Generate PGlite bootstrap SQL directly from the Stripe OpenAPI spec.
 * No Docker, no Postgres, no stripe-mock needed — runs in seconds.
 *
 * Usage:
 *   bun run scripts/explorer-generate.ts
 *   STRIPE_API_VERSION=2022-11-15 bun run scripts/explorer-generate.ts
 */

import {
  resolveOpenApiSpec,
  SpecParser,
  parsedTableToJsonSchema,
  OPENAPI_RESOURCE_TABLE_ALIASES,
} from '../packages/source-stripe/src/openapi/index.js'
import { buildCreateTableWithSchema } from '../packages/destination-postgres/src/schemaProjection.js'
import fs from 'node:fs'
import path from 'node:path'

const API_VERSION = process.env.STRIPE_API_VERSION ?? '2020-08-27'
const OUTPUT_DIR = path.join(import.meta.dir, '..', 'apps', 'visualizer', 'public', 'explorer-data')
const SCHEMA = 'stripe'

console.log(`Fetching Stripe OpenAPI spec for ${API_VERSION}...`)
const { spec, source } = await resolveOpenApiSpec({ apiVersion: API_VERSION })
console.log(`  source: ${source}`)

// Discover all table names from the spec (not just RUNTIME_REQUIRED_TABLES)
const allTableNames = new Set<string>()
for (const schemaDef of Object.values(spec.components!.schemas!)) {
  const resourceId = (schemaDef as Record<string, unknown>)['x-resourceId']
  if (!resourceId || typeof resourceId !== 'string') continue
  const alias = OPENAPI_RESOURCE_TABLE_ALIASES[resourceId]
  if (alias) {
    allTableNames.add(alias)
  } else {
    const normalized = resourceId.toLowerCase().replace(/\./g, '_')
    allTableNames.add(normalized.endsWith('s') ? normalized : `${normalized}s`)
  }
}

const parser = new SpecParser()
const parsed = parser.parse(spec, { allowedTables: Array.from(allTableNames) })
console.log(`Parsed ${parsed.tables.length} tables`)

// Generate CREATE TABLE SQL (schema-only, no data — this is a read-only explorer)
const sqlParts: string[] = [
  `-- PGlite Bootstrap SQL`,
  `-- Generated by scripts/explorer-generate.ts`,
  `-- Stripe API version: ${API_VERSION}`,
  `-- Generated: ${new Date().toISOString()}`,
  `-- Tables: ${parsed.tables.length}`,
  '',
  `CREATE SCHEMA IF NOT EXISTS "${SCHEMA}";`,
  '',
]

for (const table of parsed.tables) {
  const jsonSchema = parsedTableToJsonSchema(table)
  const stmts = buildCreateTableWithSchema(SCHEMA, table.tableName, jsonSchema, {
    system_columns: [{ name: '_account_id', type: 'text NOT NULL' }],
  })
  // Take only the CREATE TABLE statement — skip ALTER TABLE / INDEX / TRIGGER (read-only explorer)
  const createStmt = stmts[0]!.replace('CREATE TABLE ', 'CREATE TABLE IF NOT EXISTS ')
  sqlParts.push(`-- ${table.tableName}`)
  sqlParts.push(createStmt)
  sqlParts.push('')
}

fs.mkdirSync(OUTPUT_DIR, { recursive: true })

const bootstrapPath = path.join(OUTPUT_DIR, 'bootstrap.sql')
fs.writeFileSync(bootstrapPath, sqlParts.join('\n'))
const bootstrapKb = (fs.statSync(bootstrapPath).size / 1024).toFixed(1)
console.log(`Wrote bootstrap.sql (${bootstrapKb} KB, ${parsed.tables.length} tables)`)

const manifest = {
  generatedAt: new Date().toISOString(),
  apiVersion: API_VERSION,
  totalTables: parsed.tables.length,
  tables: parsed.tables.map((t) => t.tableName),
}
const manifestPath = path.join(OUTPUT_DIR, 'manifest.json')
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2))
console.log(`Wrote manifest.json`)
